// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from common.proto</summary>
public static partial class CommonReflection {

  #region Descriptor
  /// <summary>File descriptor for common.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CommonReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgxjb21tb24ucHJvdG8iJwoIVXNlckRhdGESGwoIcm9vbURhdGEYASABKAsy",
          "CS5Sb29tRGF0YSI6CghTZWF0RGF0YRIMCgRzZWF0GAEgASgFEg4KBnVzZXJJ",
          "ZBgCIAEoCRIQCgh1c2VyTmljaxgDIAEoCSKjAQoIUm9vbURhdGESKwoJc2Vh",
          "dDJEYXRhGAEgAygLMhguUm9vbURhdGEuU2VhdDJEYXRhRW50cnkSEAoIeW91",
          "clNlYXQYAiABKAUSGwoIZ2FtZURhdGEYAyABKAsyCS5HYW1lRGF0YRo7Cg5T",
          "ZWF0MkRhdGFFbnRyeRILCgNrZXkYASABKAUSGAoFdmFsdWUYAiABKAsyCS5T",
          "ZWF0RGF0YToCOAEihgEKCEdhbWVEYXRhEh0KCXJvb21TdGF0ZRgBIAEoDjIK",
          "LlJvb21TdGF0ZRIRCglyZWFkeURhdGEYAiADKAgSEQoJYm9hcmREYXRhGAMg",
          "AygFEhAKCHR1cm5TZWF0GAQgASgFEhIKCnR1cm5TeW1ib2wYBSABKAUSDwoH",
          "d2luU2VhdBgGIAEoBSqkAQoJRXJyb3JDb2RlEgYKAk9rEAASEAoMSW52YWxp",
          "ZFBhcmFtEAESDwoLU3lzdGVtRXJyb3IQAhIUCg9Mb2dpbkdhbWVfRXJyb3IQ",
          "rAISFAoPRW50ZXJSb29tX0Vycm9yEJADEiEKHEV4aXRSb29tX0Vycm9yX05v",
          "dFJlYWR5U3RhdGUQkQMSHQoYRXhpdFJvb21fRXJyb3JfTm90SW5Sb29tEJID",
          "Kk4KCVJvb21TdGF0ZRIKCgZFX05vbmUQABILCgdFX1JlYWR5EAESDwoLRV9D",
          "b3VudERvd24QAhIMCghFX0JhdHRsZRADEgkKBUVfRW5kEARCFQoTY29tLnpm",
          "b28uc2VydmVyLm1zZ2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ErrorCode), typeof(global::RoomState), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::UserData), global::UserData.Parser, new[]{ "RoomData" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SeatData), global::SeatData.Parser, new[]{ "Seat", "UserId", "UserNick" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RoomData), global::RoomData.Parser, new[]{ "Seat2Data", "YourSeat", "GameData" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::GameData), global::GameData.Parser, new[]{ "RoomState", "ReadyData", "BoardData", "TurnSeat", "TurnSymbol", "WinSeat" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
/// <summary>
///错误码
/// </summary>
public enum ErrorCode {
  /// <summary>
  //////通用错误码0-99/////
  /// </summary>
  [pbr::OriginalName("Ok")] Ok = 0,
  /// <summary>
  /// 非法参数
  /// </summary>
  [pbr::OriginalName("InvalidParam")] InvalidParam = 1,
  /// <summary>
  /// 系统错误
  /// </summary>
  [pbr::OriginalName("SystemError")] SystemError = 2,
  /// <summary>
  //////登录游戏/////
  /// </summary>
  [pbr::OriginalName("LoginGame_Error")] LoginGameError = 300,
  /// <summary>
  //////游戏房间/////
  /// </summary>
  [pbr::OriginalName("EnterRoom_Error")] EnterRoomError = 400,
  [pbr::OriginalName("ExitRoom_Error_NotReadyState")] ExitRoomErrorNotReadyState = 401,
  [pbr::OriginalName("ExitRoom_Error_NotInRoom")] ExitRoomErrorNotInRoom = 402,
}

/// <summary>
///房间状态
/// </summary>
public enum RoomState {
  /// <summary>
  /// 未初始化
  /// </summary>
  [pbr::OriginalName("E_None")] ENone = 0,
  /// <summary>
  /// 未满2人，准备中
  /// </summary>
  [pbr::OriginalName("E_Ready")] EReady = 1,
  /// <summary>
  /// 倒计时状态，结束后，进入对局状态
  /// </summary>
  [pbr::OriginalName("E_CountDown")] ECountDown = 2,
  /// <summary>
  /// 对局状态
  /// </summary>
  [pbr::OriginalName("E_Battle")] EBattle = 3,
  /// <summary>
  /// 结算
  /// </summary>
  [pbr::OriginalName("E_End")] EEnd = 4,
}

#endregion

#region Messages
/// <summary>
///User数据
/// </summary>
public sealed partial class UserData : pb::IMessage<UserData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UserData> _parser = new pb::MessageParser<UserData>(() => new UserData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UserData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserData(UserData other) : this() {
    roomData_ = other.roomData_ != null ? other.roomData_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UserData Clone() {
    return new UserData(this);
  }

  /// <summary>Field number for the "roomData" field.</summary>
  public const int RoomDataFieldNumber = 1;
  private global::RoomData roomData_;
  /// <summary>
  /// 用于实现断线重连!!!
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RoomData RoomData {
    get { return roomData_; }
    set {
      roomData_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UserData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UserData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(RoomData, other.RoomData)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (roomData_ != null) hash ^= RoomData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (roomData_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(RoomData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (roomData_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(RoomData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (roomData_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(RoomData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UserData other) {
    if (other == null) {
      return;
    }
    if (other.roomData_ != null) {
      if (roomData_ == null) {
        RoomData = new global::RoomData();
      }
      RoomData.MergeFrom(other.RoomData);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          if (roomData_ == null) {
            RoomData = new global::RoomData();
          }
          input.ReadMessage(RoomData);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          if (roomData_ == null) {
            RoomData = new global::RoomData();
          }
          input.ReadMessage(RoomData);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///位置用户数据
/// </summary>
public sealed partial class SeatData : pb::IMessage<SeatData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SeatData> _parser = new pb::MessageParser<SeatData>(() => new SeatData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SeatData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SeatData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SeatData(SeatData other) : this() {
    seat_ = other.seat_;
    userId_ = other.userId_;
    userNick_ = other.userNick_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SeatData Clone() {
    return new SeatData(this);
  }

  /// <summary>Field number for the "seat" field.</summary>
  public const int SeatFieldNumber = 1;
  private int seat_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Seat {
    get { return seat_; }
    set {
      seat_ = value;
    }
  }

  /// <summary>Field number for the "userId" field.</summary>
  public const int UserIdFieldNumber = 2;
  private string userId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserId {
    get { return userId_; }
    set {
      userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "userNick" field.</summary>
  public const int UserNickFieldNumber = 3;
  private string userNick_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UserNick {
    get { return userNick_; }
    set {
      userNick_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SeatData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SeatData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Seat != other.Seat) return false;
    if (UserId != other.UserId) return false;
    if (UserNick != other.UserNick) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Seat != 0) hash ^= Seat.GetHashCode();
    if (UserId.Length != 0) hash ^= UserId.GetHashCode();
    if (UserNick.Length != 0) hash ^= UserNick.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Seat != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Seat);
    }
    if (UserId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(UserId);
    }
    if (UserNick.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(UserNick);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Seat != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Seat);
    }
    if (UserId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(UserId);
    }
    if (UserNick.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(UserNick);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Seat != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seat);
    }
    if (UserId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
    }
    if (UserNick.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UserNick);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SeatData other) {
    if (other == null) {
      return;
    }
    if (other.Seat != 0) {
      Seat = other.Seat;
    }
    if (other.UserId.Length != 0) {
      UserId = other.UserId;
    }
    if (other.UserNick.Length != 0) {
      UserNick = other.UserNick;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Seat = input.ReadInt32();
          break;
        }
        case 18: {
          UserId = input.ReadString();
          break;
        }
        case 26: {
          UserNick = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Seat = input.ReadInt32();
          break;
        }
        case 18: {
          UserId = input.ReadString();
          break;
        }
        case 26: {
          UserNick = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///房间数据
/// </summary>
public sealed partial class RoomData : pb::IMessage<RoomData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<RoomData> _parser = new pb::MessageParser<RoomData>(() => new RoomData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<RoomData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RoomData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RoomData(RoomData other) : this() {
    seat2Data_ = other.seat2Data_.Clone();
    yourSeat_ = other.yourSeat_;
    gameData_ = other.gameData_ != null ? other.gameData_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public RoomData Clone() {
    return new RoomData(this);
  }

  /// <summary>Field number for the "seat2Data" field.</summary>
  public const int Seat2DataFieldNumber = 1;
  private static readonly pbc::MapField<int, global::SeatData>.Codec _map_seat2Data_codec
      = new pbc::MapField<int, global::SeatData>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::SeatData.Parser), 10);
  private readonly pbc::MapField<int, global::SeatData> seat2Data_ = new pbc::MapField<int, global::SeatData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<int, global::SeatData> Seat2Data {
    get { return seat2Data_; }
  }

  /// <summary>Field number for the "yourSeat" field.</summary>
  public const int YourSeatFieldNumber = 2;
  private int yourSeat_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int YourSeat {
    get { return yourSeat_; }
    set {
      yourSeat_ = value;
    }
  }

  /// <summary>Field number for the "gameData" field.</summary>
  public const int GameDataFieldNumber = 3;
  private global::GameData gameData_;
  /// <summary>
  /// 游戏数据
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::GameData GameData {
    get { return gameData_; }
    set {
      gameData_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as RoomData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(RoomData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!Seat2Data.Equals(other.Seat2Data)) return false;
    if (YourSeat != other.YourSeat) return false;
    if (!object.Equals(GameData, other.GameData)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= Seat2Data.GetHashCode();
    if (YourSeat != 0) hash ^= YourSeat.GetHashCode();
    if (gameData_ != null) hash ^= GameData.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    seat2Data_.WriteTo(output, _map_seat2Data_codec);
    if (YourSeat != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(YourSeat);
    }
    if (gameData_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(GameData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    seat2Data_.WriteTo(ref output, _map_seat2Data_codec);
    if (YourSeat != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(YourSeat);
    }
    if (gameData_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(GameData);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += seat2Data_.CalculateSize(_map_seat2Data_codec);
    if (YourSeat != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(YourSeat);
    }
    if (gameData_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameData);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(RoomData other) {
    if (other == null) {
      return;
    }
    seat2Data_.Add(other.seat2Data_);
    if (other.YourSeat != 0) {
      YourSeat = other.YourSeat;
    }
    if (other.gameData_ != null) {
      if (gameData_ == null) {
        GameData = new global::GameData();
      }
      GameData.MergeFrom(other.GameData);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          seat2Data_.AddEntriesFrom(input, _map_seat2Data_codec);
          break;
        }
        case 16: {
          YourSeat = input.ReadInt32();
          break;
        }
        case 26: {
          if (gameData_ == null) {
            GameData = new global::GameData();
          }
          input.ReadMessage(GameData);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          seat2Data_.AddEntriesFrom(ref input, _map_seat2Data_codec);
          break;
        }
        case 16: {
          YourSeat = input.ReadInt32();
          break;
        }
        case 26: {
          if (gameData_ == null) {
            GameData = new global::GameData();
          }
          input.ReadMessage(GameData);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///井字棋对局数据
/// </summary>
public sealed partial class GameData : pb::IMessage<GameData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GameData> _parser = new pb::MessageParser<GameData>(() => new GameData());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GameData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CommonReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameData(GameData other) : this() {
    roomState_ = other.roomState_;
    readyData_ = other.readyData_.Clone();
    boardData_ = other.boardData_.Clone();
    turnSeat_ = other.turnSeat_;
    turnSymbol_ = other.turnSymbol_;
    winSeat_ = other.winSeat_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameData Clone() {
    return new GameData(this);
  }

  /// <summary>Field number for the "roomState" field.</summary>
  public const int RoomStateFieldNumber = 1;
  private global::RoomState roomState_ = global::RoomState.ENone;
  /// <summary>
  /// 房间状态
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::RoomState RoomState {
    get { return roomState_; }
    set {
      roomState_ = value;
    }
  }

  /// <summary>Field number for the "readyData" field.</summary>
  public const int ReadyDataFieldNumber = 2;
  private static readonly pb::FieldCodec<bool> _repeated_readyData_codec
      = pb::FieldCodec.ForBool(18);
  private readonly pbc::RepeatedField<bool> readyData_ = new pbc::RepeatedField<bool>();
  /// <summary>
  /// E_Ready
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<bool> ReadyData {
    get { return readyData_; }
  }

  /// <summary>Field number for the "boardData" field.</summary>
  public const int BoardDataFieldNumber = 3;
  private static readonly pb::FieldCodec<int> _repeated_boardData_codec
      = pb::FieldCodec.ForInt32(26);
  private readonly pbc::RepeatedField<int> boardData_ = new pbc::RepeatedField<int>();
  /// <summary>
  /// E_Battle(以0号玩家的角度)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> BoardData {
    get { return boardData_; }
  }

  /// <summary>Field number for the "turnSeat" field.</summary>
  public const int TurnSeatFieldNumber = 4;
  private int turnSeat_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TurnSeat {
    get { return turnSeat_; }
    set {
      turnSeat_ = value;
    }
  }

  /// <summary>Field number for the "turnSymbol" field.</summary>
  public const int TurnSymbolFieldNumber = 5;
  private int turnSymbol_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TurnSymbol {
    get { return turnSymbol_; }
    set {
      turnSymbol_ = value;
    }
  }

  /// <summary>Field number for the "winSeat" field.</summary>
  public const int WinSeatFieldNumber = 6;
  private int winSeat_;
  /// <summary>
  /// E_End
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int WinSeat {
    get { return winSeat_; }
    set {
      winSeat_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GameData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GameData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RoomState != other.RoomState) return false;
    if(!readyData_.Equals(other.readyData_)) return false;
    if(!boardData_.Equals(other.boardData_)) return false;
    if (TurnSeat != other.TurnSeat) return false;
    if (TurnSymbol != other.TurnSymbol) return false;
    if (WinSeat != other.WinSeat) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (RoomState != global::RoomState.ENone) hash ^= RoomState.GetHashCode();
    hash ^= readyData_.GetHashCode();
    hash ^= boardData_.GetHashCode();
    if (TurnSeat != 0) hash ^= TurnSeat.GetHashCode();
    if (TurnSymbol != 0) hash ^= TurnSymbol.GetHashCode();
    if (WinSeat != 0) hash ^= WinSeat.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (RoomState != global::RoomState.ENone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) RoomState);
    }
    readyData_.WriteTo(output, _repeated_readyData_codec);
    boardData_.WriteTo(output, _repeated_boardData_codec);
    if (TurnSeat != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(TurnSeat);
    }
    if (TurnSymbol != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(TurnSymbol);
    }
    if (WinSeat != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(WinSeat);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (RoomState != global::RoomState.ENone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) RoomState);
    }
    readyData_.WriteTo(ref output, _repeated_readyData_codec);
    boardData_.WriteTo(ref output, _repeated_boardData_codec);
    if (TurnSeat != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(TurnSeat);
    }
    if (TurnSymbol != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(TurnSymbol);
    }
    if (WinSeat != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(WinSeat);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (RoomState != global::RoomState.ENone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RoomState);
    }
    size += readyData_.CalculateSize(_repeated_readyData_codec);
    size += boardData_.CalculateSize(_repeated_boardData_codec);
    if (TurnSeat != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TurnSeat);
    }
    if (TurnSymbol != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TurnSymbol);
    }
    if (WinSeat != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(WinSeat);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GameData other) {
    if (other == null) {
      return;
    }
    if (other.RoomState != global::RoomState.ENone) {
      RoomState = other.RoomState;
    }
    readyData_.Add(other.readyData_);
    boardData_.Add(other.boardData_);
    if (other.TurnSeat != 0) {
      TurnSeat = other.TurnSeat;
    }
    if (other.TurnSymbol != 0) {
      TurnSymbol = other.TurnSymbol;
    }
    if (other.WinSeat != 0) {
      WinSeat = other.WinSeat;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          RoomState = (global::RoomState) input.ReadEnum();
          break;
        }
        case 18:
        case 16: {
          readyData_.AddEntriesFrom(input, _repeated_readyData_codec);
          break;
        }
        case 26:
        case 24: {
          boardData_.AddEntriesFrom(input, _repeated_boardData_codec);
          break;
        }
        case 32: {
          TurnSeat = input.ReadInt32();
          break;
        }
        case 40: {
          TurnSymbol = input.ReadInt32();
          break;
        }
        case 48: {
          WinSeat = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          RoomState = (global::RoomState) input.ReadEnum();
          break;
        }
        case 18:
        case 16: {
          readyData_.AddEntriesFrom(ref input, _repeated_readyData_codec);
          break;
        }
        case 26:
        case 24: {
          boardData_.AddEntriesFrom(ref input, _repeated_boardData_codec);
          break;
        }
        case 32: {
          TurnSeat = input.ReadInt32();
          break;
        }
        case 40: {
          TurnSymbol = input.ReadInt32();
          break;
        }
        case 48: {
          WinSeat = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
