// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: msgId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from msgId.proto</summary>
public static partial class MsgIdReflection {

  #region Descriptor
  /// <summary>File descriptor for msgId.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MsgIdReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgttc2dJZC5wcm90byqlAwoGTXNnSWRzEgsKB0lOVkFMSUQQABIQCgpfTG9n",
          "aW5HYW1lEJXrARIUCg5fTG9naW5HYW1lUmVzcBCW6wESEAoKX0VudGVyUm9v",
          "bRD56wESFAoOX0VudGVyUm9vbVJlc3AQ+usBEg8KCV9FeGl0Um9vbRD76wES",
          "EwoNX0V4aXRSb29tUmVzcBD86wESGQoTX05vdGlmeU9uZUVudGVyUm9vbRD9",
          "6wESGAoSX05vdGlmeU9uZUV4aXRSb29tEP7rARIPCglfT25lUmVhZHkQ/+sB",
          "EhMKDV9PbmVSZWFkeVJlc3AQgOwBEhUKD19Ob3RpZnlPbmVSZWFkeRCB7AES",
          "GAoSX05vdGlmeUJhdHRsZVN0YXJ0EILsARIWChBfTm90aWZ5Q291bnREb3du",
          "EIPsARIOCghfT25lVHVybhCE7AESFAoOX05vdGlmeU9uZVR1cm4QhewBEhsK",
          "FV9Ob3RpZnlUcmlnZ2VyT25lVHVybhCG7AESFgoQX05vdGlmeUJhdHRsZUVu",
          "ZBCH7AESGQoTX05vdGlmeVRyaWdnZXJSZWFkeRCI7AFCFQoTY29tLnpmb28u",
          "c2VydmVyLm1zZ2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MsgIds), }, null, null));
  }
  #endregion

}
#region Enums
public enum MsgIds {
  [pbr::OriginalName("INVALID")] Invalid = 0,
  /// <summary>
  ////// 登录 /////
  /// </summary>
  [pbr::OriginalName("_LoginGame")] LoginGame = 30101,
  [pbr::OriginalName("_LoginGameResp")] LoginGameResp = 30102,
  /// <summary>
  ////// 游戏逻辑 /////
  /// </summary>
  [pbr::OriginalName("_EnterRoom")] EnterRoom = 30201,
  [pbr::OriginalName("_EnterRoomResp")] EnterRoomResp = 30202,
  [pbr::OriginalName("_ExitRoom")] ExitRoom = 30203,
  [pbr::OriginalName("_ExitRoomResp")] ExitRoomResp = 30204,
  [pbr::OriginalName("_NotifyOneEnterRoom")] NotifyOneEnterRoom = 30205,
  [pbr::OriginalName("_NotifyOneExitRoom")] NotifyOneExitRoom = 30206,
  [pbr::OriginalName("_OneReady")] OneReady = 30207,
  [pbr::OriginalName("_OneReadyResp")] OneReadyResp = 30208,
  [pbr::OriginalName("_NotifyOneReady")] NotifyOneReady = 30209,
  [pbr::OriginalName("_NotifyBattleStart")] NotifyBattleStart = 30210,
  [pbr::OriginalName("_NotifyCountDown")] NotifyCountDown = 30211,
  [pbr::OriginalName("_OneTurn")] OneTurn = 30212,
  [pbr::OriginalName("_NotifyOneTurn")] NotifyOneTurn = 30213,
  [pbr::OriginalName("_NotifyTriggerOneTurn")] NotifyTriggerOneTurn = 30214,
  [pbr::OriginalName("_NotifyBattleEnd")] NotifyBattleEnd = 30215,
  [pbr::OriginalName("_NotifyTriggerReady")] NotifyTriggerReady = 30216,
}

#endregion


#endregion Designer generated code
