spring.application.name=gateway
server.port=8082

app.mongo.uri=mongodb://127.0.0.1:37017
app.mongo.database=kt_zfoo

redisson.address=redis://127.0.0.1:36379
redisson.database=0
redisson.password=redis_password

game.server.count=10
game.server.name-prefix=server-
game.server.ip=127.0.0.1
game.server.port=1111
