// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.zfoo.server.msg;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginGameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginGame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string token = 1;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 1;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * <pre>
   *使用token登录(也就是:使用long类型的userId登录,暂时就先不搞Role了)
   * </pre>
   *
   * Protobuf type {@code LoginGame}
   */
  public static final class LoginGame extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginGame)
      LoginGameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginGame.newBuilder() to construct.
    private LoginGame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginGame() {
      token_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginGame();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zfoo.server.msg.Login.internal_static_LoginGame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zfoo.server.msg.Login.internal_static_LoginGame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zfoo.server.msg.Login.LoginGame.class, com.zfoo.server.msg.Login.LoginGame.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object token_ = "";
    /**
     * <code>string token = 1;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 1;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zfoo.server.msg.Login.LoginGame)) {
        return super.equals(obj);
      }
      com.zfoo.server.msg.Login.LoginGame other = (com.zfoo.server.msg.Login.LoginGame) obj;

      if (!getToken()
          .equals(other.getToken())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zfoo.server.msg.Login.LoginGame parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zfoo.server.msg.Login.LoginGame parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zfoo.server.msg.Login.LoginGame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zfoo.server.msg.Login.LoginGame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zfoo.server.msg.Login.LoginGame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zfoo.server.msg.Login.LoginGame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zfoo.server.msg.Login.LoginGame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zfoo.server.msg.Login.LoginGame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zfoo.server.msg.Login.LoginGame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zfoo.server.msg.Login.LoginGame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zfoo.server.msg.Login.LoginGame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zfoo.server.msg.Login.LoginGame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zfoo.server.msg.Login.LoginGame prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *使用token登录(也就是:使用long类型的userId登录,暂时就先不搞Role了)
     * </pre>
     *
     * Protobuf type {@code LoginGame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginGame)
        com.zfoo.server.msg.Login.LoginGameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zfoo.server.msg.Login.internal_static_LoginGame_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zfoo.server.msg.Login.internal_static_LoginGame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zfoo.server.msg.Login.LoginGame.class, com.zfoo.server.msg.Login.LoginGame.Builder.class);
      }

      // Construct using com.zfoo.server.msg.Login.LoginGame.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        token_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zfoo.server.msg.Login.internal_static_LoginGame_descriptor;
      }

      @java.lang.Override
      public com.zfoo.server.msg.Login.LoginGame getDefaultInstanceForType() {
        return com.zfoo.server.msg.Login.LoginGame.getDefaultInstance();
      }

      @java.lang.Override
      public com.zfoo.server.msg.Login.LoginGame build() {
        com.zfoo.server.msg.Login.LoginGame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zfoo.server.msg.Login.LoginGame buildPartial() {
        com.zfoo.server.msg.Login.LoginGame result = new com.zfoo.server.msg.Login.LoginGame(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.zfoo.server.msg.Login.LoginGame result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.token_ = token_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zfoo.server.msg.Login.LoginGame) {
          return mergeFrom((com.zfoo.server.msg.Login.LoginGame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zfoo.server.msg.Login.LoginGame other) {
        if (other == com.zfoo.server.msg.Login.LoginGame.getDefaultInstance()) return this;
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                token_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 1;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        token_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        token_ = getDefaultInstance().getToken();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        token_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginGame)
    }

    // @@protoc_insertion_point(class_scope:LoginGame)
    private static final com.zfoo.server.msg.Login.LoginGame DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zfoo.server.msg.Login.LoginGame();
    }

    public static com.zfoo.server.msg.Login.LoginGame getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginGame>
        PARSER = new com.google.protobuf.AbstractParser<LoginGame>() {
      @java.lang.Override
      public LoginGame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginGame> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginGame> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zfoo.server.msg.Login.LoginGame getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginGameRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginGameResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ErrorCode errorCode = 1;</code>
     * @return The enum numeric value on the wire for errorCode.
     */
    int getErrorCodeValue();
    /**
     * <code>.ErrorCode errorCode = 1;</code>
     * @return The errorCode.
     */
    com.zfoo.server.msg.Common.ErrorCode getErrorCode();

    /**
     * <code>.UserData userData = 2;</code>
     * @return Whether the userData field is set.
     */
    boolean hasUserData();
    /**
     * <code>.UserData userData = 2;</code>
     * @return The userData.
     */
    com.zfoo.server.msg.Common.UserData getUserData();
    /**
     * <code>.UserData userData = 2;</code>
     */
    com.zfoo.server.msg.Common.UserDataOrBuilder getUserDataOrBuilder();
  }
  /**
   * <pre>
   * 主要是验证token,游戏进入online状态
   * </pre>
   *
   * Protobuf type {@code LoginGameResp}
   */
  public static final class LoginGameResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LoginGameResp)
      LoginGameRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginGameResp.newBuilder() to construct.
    private LoginGameResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginGameResp() {
      errorCode_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginGameResp();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zfoo.server.msg.Login.internal_static_LoginGameResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zfoo.server.msg.Login.internal_static_LoginGameResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zfoo.server.msg.Login.LoginGameResp.class, com.zfoo.server.msg.Login.LoginGameResp.Builder.class);
    }

    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_ = 0;
    /**
     * <code>.ErrorCode errorCode = 1;</code>
     * @return The enum numeric value on the wire for errorCode.
     */
    @java.lang.Override public int getErrorCodeValue() {
      return errorCode_;
    }
    /**
     * <code>.ErrorCode errorCode = 1;</code>
     * @return The errorCode.
     */
    @java.lang.Override public com.zfoo.server.msg.Common.ErrorCode getErrorCode() {
      com.zfoo.server.msg.Common.ErrorCode result = com.zfoo.server.msg.Common.ErrorCode.forNumber(errorCode_);
      return result == null ? com.zfoo.server.msg.Common.ErrorCode.UNRECOGNIZED : result;
    }

    public static final int USERDATA_FIELD_NUMBER = 2;
    private com.zfoo.server.msg.Common.UserData userData_;
    /**
     * <code>.UserData userData = 2;</code>
     * @return Whether the userData field is set.
     */
    @java.lang.Override
    public boolean hasUserData() {
      return userData_ != null;
    }
    /**
     * <code>.UserData userData = 2;</code>
     * @return The userData.
     */
    @java.lang.Override
    public com.zfoo.server.msg.Common.UserData getUserData() {
      return userData_ == null ? com.zfoo.server.msg.Common.UserData.getDefaultInstance() : userData_;
    }
    /**
     * <code>.UserData userData = 2;</code>
     */
    @java.lang.Override
    public com.zfoo.server.msg.Common.UserDataOrBuilder getUserDataOrBuilder() {
      return userData_ == null ? com.zfoo.server.msg.Common.UserData.getDefaultInstance() : userData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errorCode_ != com.zfoo.server.msg.Common.ErrorCode.Ok.getNumber()) {
        output.writeEnum(1, errorCode_);
      }
      if (userData_ != null) {
        output.writeMessage(2, getUserData());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errorCode_ != com.zfoo.server.msg.Common.ErrorCode.Ok.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, errorCode_);
      }
      if (userData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUserData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zfoo.server.msg.Login.LoginGameResp)) {
        return super.equals(obj);
      }
      com.zfoo.server.msg.Login.LoginGameResp other = (com.zfoo.server.msg.Login.LoginGameResp) obj;

      if (errorCode_ != other.errorCode_) return false;
      if (hasUserData() != other.hasUserData()) return false;
      if (hasUserData()) {
        if (!getUserData()
            .equals(other.getUserData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + errorCode_;
      if (hasUserData()) {
        hash = (37 * hash) + USERDATA_FIELD_NUMBER;
        hash = (53 * hash) + getUserData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zfoo.server.msg.Login.LoginGameResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zfoo.server.msg.Login.LoginGameResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zfoo.server.msg.Login.LoginGameResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zfoo.server.msg.Login.LoginGameResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zfoo.server.msg.Login.LoginGameResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zfoo.server.msg.Login.LoginGameResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zfoo.server.msg.Login.LoginGameResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zfoo.server.msg.Login.LoginGameResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zfoo.server.msg.Login.LoginGameResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zfoo.server.msg.Login.LoginGameResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zfoo.server.msg.Login.LoginGameResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zfoo.server.msg.Login.LoginGameResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zfoo.server.msg.Login.LoginGameResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 主要是验证token,游戏进入online状态
     * </pre>
     *
     * Protobuf type {@code LoginGameResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginGameResp)
        com.zfoo.server.msg.Login.LoginGameRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zfoo.server.msg.Login.internal_static_LoginGameResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zfoo.server.msg.Login.internal_static_LoginGameResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zfoo.server.msg.Login.LoginGameResp.class, com.zfoo.server.msg.Login.LoginGameResp.Builder.class);
      }

      // Construct using com.zfoo.server.msg.Login.LoginGameResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        errorCode_ = 0;
        userData_ = null;
        if (userDataBuilder_ != null) {
          userDataBuilder_.dispose();
          userDataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zfoo.server.msg.Login.internal_static_LoginGameResp_descriptor;
      }

      @java.lang.Override
      public com.zfoo.server.msg.Login.LoginGameResp getDefaultInstanceForType() {
        return com.zfoo.server.msg.Login.LoginGameResp.getDefaultInstance();
      }

      @java.lang.Override
      public com.zfoo.server.msg.Login.LoginGameResp build() {
        com.zfoo.server.msg.Login.LoginGameResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.zfoo.server.msg.Login.LoginGameResp buildPartial() {
        com.zfoo.server.msg.Login.LoginGameResp result = new com.zfoo.server.msg.Login.LoginGameResp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.zfoo.server.msg.Login.LoginGameResp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.errorCode_ = errorCode_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userData_ = userDataBuilder_ == null
              ? userData_
              : userDataBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zfoo.server.msg.Login.LoginGameResp) {
          return mergeFrom((com.zfoo.server.msg.Login.LoginGameResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zfoo.server.msg.Login.LoginGameResp other) {
        if (other == com.zfoo.server.msg.Login.LoginGameResp.getDefaultInstance()) return this;
        if (other.errorCode_ != 0) {
          setErrorCodeValue(other.getErrorCodeValue());
        }
        if (other.hasUserData()) {
          mergeUserData(other.getUserData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                errorCode_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getUserDataFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int errorCode_ = 0;
      /**
       * <code>.ErrorCode errorCode = 1;</code>
       * @return The enum numeric value on the wire for errorCode.
       */
      @java.lang.Override public int getErrorCodeValue() {
        return errorCode_;
      }
      /**
       * <code>.ErrorCode errorCode = 1;</code>
       * @param value The enum numeric value on the wire for errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCodeValue(int value) {
        errorCode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ErrorCode errorCode = 1;</code>
       * @return The errorCode.
       */
      @java.lang.Override
      public com.zfoo.server.msg.Common.ErrorCode getErrorCode() {
        com.zfoo.server.msg.Common.ErrorCode result = com.zfoo.server.msg.Common.ErrorCode.forNumber(errorCode_);
        return result == null ? com.zfoo.server.msg.Common.ErrorCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.ErrorCode errorCode = 1;</code>
       * @param value The errorCode to set.
       * @return This builder for chaining.
       */
      public Builder setErrorCode(com.zfoo.server.msg.Common.ErrorCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        errorCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ErrorCode errorCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private com.zfoo.server.msg.Common.UserData userData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zfoo.server.msg.Common.UserData, com.zfoo.server.msg.Common.UserData.Builder, com.zfoo.server.msg.Common.UserDataOrBuilder> userDataBuilder_;
      /**
       * <code>.UserData userData = 2;</code>
       * @return Whether the userData field is set.
       */
      public boolean hasUserData() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.UserData userData = 2;</code>
       * @return The userData.
       */
      public com.zfoo.server.msg.Common.UserData getUserData() {
        if (userDataBuilder_ == null) {
          return userData_ == null ? com.zfoo.server.msg.Common.UserData.getDefaultInstance() : userData_;
        } else {
          return userDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.UserData userData = 2;</code>
       */
      public Builder setUserData(com.zfoo.server.msg.Common.UserData value) {
        if (userDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userData_ = value;
        } else {
          userDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.UserData userData = 2;</code>
       */
      public Builder setUserData(
          com.zfoo.server.msg.Common.UserData.Builder builderForValue) {
        if (userDataBuilder_ == null) {
          userData_ = builderForValue.build();
        } else {
          userDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.UserData userData = 2;</code>
       */
      public Builder mergeUserData(com.zfoo.server.msg.Common.UserData value) {
        if (userDataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            userData_ != null &&
            userData_ != com.zfoo.server.msg.Common.UserData.getDefaultInstance()) {
            getUserDataBuilder().mergeFrom(value);
          } else {
            userData_ = value;
          }
        } else {
          userDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.UserData userData = 2;</code>
       */
      public Builder clearUserData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userData_ = null;
        if (userDataBuilder_ != null) {
          userDataBuilder_.dispose();
          userDataBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.UserData userData = 2;</code>
       */
      public com.zfoo.server.msg.Common.UserData.Builder getUserDataBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUserDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.UserData userData = 2;</code>
       */
      public com.zfoo.server.msg.Common.UserDataOrBuilder getUserDataOrBuilder() {
        if (userDataBuilder_ != null) {
          return userDataBuilder_.getMessageOrBuilder();
        } else {
          return userData_ == null ?
              com.zfoo.server.msg.Common.UserData.getDefaultInstance() : userData_;
        }
      }
      /**
       * <code>.UserData userData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zfoo.server.msg.Common.UserData, com.zfoo.server.msg.Common.UserData.Builder, com.zfoo.server.msg.Common.UserDataOrBuilder> 
          getUserDataFieldBuilder() {
        if (userDataBuilder_ == null) {
          userDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zfoo.server.msg.Common.UserData, com.zfoo.server.msg.Common.UserData.Builder, com.zfoo.server.msg.Common.UserDataOrBuilder>(
                  getUserData(),
                  getParentForChildren(),
                  isClean());
          userData_ = null;
        }
        return userDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LoginGameResp)
    }

    // @@protoc_insertion_point(class_scope:LoginGameResp)
    private static final com.zfoo.server.msg.Login.LoginGameResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zfoo.server.msg.Login.LoginGameResp();
    }

    public static com.zfoo.server.msg.Login.LoginGameResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginGameResp>
        PARSER = new com.google.protobuf.AbstractParser<LoginGameResp>() {
      @java.lang.Override
      public LoginGameResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginGameResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginGameResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.zfoo.server.msg.Login.LoginGameResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginGame_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginGame_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginGameResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginGameResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\032\014common.proto\"\032\n\tLoginGame" +
      "\022\r\n\005token\030\001 \001(\t\"K\n\rLoginGameResp\022\035\n\terro" +
      "rCode\030\001 \001(\0162\n.ErrorCode\022\033\n\010userData\030\002 \001(" +
      "\0132\t.UserDataB\025\n\023com.zfoo.server.msgb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zfoo.server.msg.Common.getDescriptor(),
        });
    internal_static_LoginGame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginGame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginGame_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_LoginGameResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginGameResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginGameResp_descriptor,
        new java.lang.String[] { "ErrorCode", "UserData", });
    com.zfoo.server.msg.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
