// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgId.proto

package com.zfoo.server.msg;

public final class MsgId {
  private MsgId() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MsgIds}
   */
  public enum MsgIds
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>INVALID = 0;</code>
     */
    INVALID(0),
    /**
     * <pre>
     *&#47;// 登录 /////
     * </pre>
     *
     * <code>_LoginGame = 30101;</code>
     */
    _LoginGame(30101),
    /**
     * <code>_LoginGameResp = 30102;</code>
     */
    _LoginGameResp(30102),
    /**
     * <pre>
     *&#47;// 游戏逻辑 /////
     * </pre>
     *
     * <code>_EnterRoom = 30201;</code>
     */
    _EnterRoom(30201),
    /**
     * <code>_EnterRoomResp = 30202;</code>
     */
    _EnterRoomResp(30202),
    /**
     * <code>_ExitRoom = 30203;</code>
     */
    _ExitRoom(30203),
    /**
     * <code>_ExitRoomResp = 30204;</code>
     */
    _ExitRoomResp(30204),
    /**
     * <code>_NotifyOneEnterRoom = 30205;</code>
     */
    _NotifyOneEnterRoom(30205),
    /**
     * <code>_NotifyOneExitRoom = 30206;</code>
     */
    _NotifyOneExitRoom(30206),
    /**
     * <code>_OneReady = 30207;</code>
     */
    _OneReady(30207),
    /**
     * <code>_OneReadyResp = 30208;</code>
     */
    _OneReadyResp(30208),
    /**
     * <code>_NotifyOneReady = 30209;</code>
     */
    _NotifyOneReady(30209),
    /**
     * <code>_NotifyBattleStart = 30210;</code>
     */
    _NotifyBattleStart(30210),
    /**
     * <code>_NotifyCountDown = 30211;</code>
     */
    _NotifyCountDown(30211),
    /**
     * <code>_OneTurn = 30212;</code>
     */
    _OneTurn(30212),
    /**
     * <code>_NotifyOneTurn = 30213;</code>
     */
    _NotifyOneTurn(30213),
    /**
     * <code>_NotifyTriggerOneTurn = 30214;</code>
     */
    _NotifyTriggerOneTurn(30214),
    /**
     * <code>_NotifyBattleEnd = 30215;</code>
     */
    _NotifyBattleEnd(30215),
    /**
     * <code>_NotifyTriggerReady = 30216;</code>
     */
    _NotifyTriggerReady(30216),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>INVALID = 0;</code>
     */
    public static final int INVALID_VALUE = 0;
    /**
     * <pre>
     *&#47;// 登录 /////
     * </pre>
     *
     * <code>_LoginGame = 30101;</code>
     */
    public static final int _LoginGame_VALUE = 30101;
    /**
     * <code>_LoginGameResp = 30102;</code>
     */
    public static final int _LoginGameResp_VALUE = 30102;
    /**
     * <pre>
     *&#47;// 游戏逻辑 /////
     * </pre>
     *
     * <code>_EnterRoom = 30201;</code>
     */
    public static final int _EnterRoom_VALUE = 30201;
    /**
     * <code>_EnterRoomResp = 30202;</code>
     */
    public static final int _EnterRoomResp_VALUE = 30202;
    /**
     * <code>_ExitRoom = 30203;</code>
     */
    public static final int _ExitRoom_VALUE = 30203;
    /**
     * <code>_ExitRoomResp = 30204;</code>
     */
    public static final int _ExitRoomResp_VALUE = 30204;
    /**
     * <code>_NotifyOneEnterRoom = 30205;</code>
     */
    public static final int _NotifyOneEnterRoom_VALUE = 30205;
    /**
     * <code>_NotifyOneExitRoom = 30206;</code>
     */
    public static final int _NotifyOneExitRoom_VALUE = 30206;
    /**
     * <code>_OneReady = 30207;</code>
     */
    public static final int _OneReady_VALUE = 30207;
    /**
     * <code>_OneReadyResp = 30208;</code>
     */
    public static final int _OneReadyResp_VALUE = 30208;
    /**
     * <code>_NotifyOneReady = 30209;</code>
     */
    public static final int _NotifyOneReady_VALUE = 30209;
    /**
     * <code>_NotifyBattleStart = 30210;</code>
     */
    public static final int _NotifyBattleStart_VALUE = 30210;
    /**
     * <code>_NotifyCountDown = 30211;</code>
     */
    public static final int _NotifyCountDown_VALUE = 30211;
    /**
     * <code>_OneTurn = 30212;</code>
     */
    public static final int _OneTurn_VALUE = 30212;
    /**
     * <code>_NotifyOneTurn = 30213;</code>
     */
    public static final int _NotifyOneTurn_VALUE = 30213;
    /**
     * <code>_NotifyTriggerOneTurn = 30214;</code>
     */
    public static final int _NotifyTriggerOneTurn_VALUE = 30214;
    /**
     * <code>_NotifyBattleEnd = 30215;</code>
     */
    public static final int _NotifyBattleEnd_VALUE = 30215;
    /**
     * <code>_NotifyTriggerReady = 30216;</code>
     */
    public static final int _NotifyTriggerReady_VALUE = 30216;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgIds valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgIds forNumber(int value) {
      switch (value) {
        case 0: return INVALID;
        case 30101: return _LoginGame;
        case 30102: return _LoginGameResp;
        case 30201: return _EnterRoom;
        case 30202: return _EnterRoomResp;
        case 30203: return _ExitRoom;
        case 30204: return _ExitRoomResp;
        case 30205: return _NotifyOneEnterRoom;
        case 30206: return _NotifyOneExitRoom;
        case 30207: return _OneReady;
        case 30208: return _OneReadyResp;
        case 30209: return _NotifyOneReady;
        case 30210: return _NotifyBattleStart;
        case 30211: return _NotifyCountDown;
        case 30212: return _OneTurn;
        case 30213: return _NotifyOneTurn;
        case 30214: return _NotifyTriggerOneTurn;
        case 30215: return _NotifyBattleEnd;
        case 30216: return _NotifyTriggerReady;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgIds>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgIds> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgIds>() {
            public MsgIds findValueByNumber(int number) {
              return MsgIds.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zfoo.server.msg.MsgId.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgIds[] VALUES = values();

    public static MsgIds valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgIds(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MsgIds)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013msgId.proto*\245\003\n\006MsgIds\022\013\n\007INVALID\020\000\022\020\n" +
      "\n_LoginGame\020\225\353\001\022\024\n\016_LoginGameResp\020\226\353\001\022\020\n" +
      "\n_EnterRoom\020\371\353\001\022\024\n\016_EnterRoomResp\020\372\353\001\022\017\n" +
      "\t_ExitRoom\020\373\353\001\022\023\n\r_ExitRoomResp\020\374\353\001\022\031\n\023_" +
      "NotifyOneEnterRoom\020\375\353\001\022\030\n\022_NotifyOneExit" +
      "Room\020\376\353\001\022\017\n\t_OneReady\020\377\353\001\022\023\n\r_OneReadyRe" +
      "sp\020\200\354\001\022\025\n\017_NotifyOneReady\020\201\354\001\022\030\n\022_Notify" +
      "BattleStart\020\202\354\001\022\026\n\020_NotifyCountDown\020\203\354\001\022" +
      "\016\n\010_OneTurn\020\204\354\001\022\024\n\016_NotifyOneTurn\020\205\354\001\022\033\n" +
      "\025_NotifyTriggerOneTurn\020\206\354\001\022\026\n\020_NotifyBat" +
      "tleEnd\020\207\354\001\022\031\n\023_NotifyTriggerReady\020\210\354\001B\025\n" +
      "\023com.zfoo.server.msgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
